name: Healthcheck scheduled

on:
  schedule:
    - cron: '15 * * * *'

jobs:
  health_check:
    runs-on: ubuntu-18.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://guarded-lowlands-80731.herokuapp.com
          max-attempts: 3
          retry-delay: 5s
